### PR TITLE
Reworked the circleci file to upload releases to Github.

### PR DESCRIPTION
**Pull request by Rembane**
Moved circleci configuration file from circle.yml to
.circleci/config.yml to automatically work with circleci.com.

Removed lens-aeson since it isn't used.

Gave stm-containers an exact hard version bound to make the project
build with cabal new-build.

### CODE REVIEW

**Comment by Rembane** [comment]
@diogob I just saw that that you had self-assigned the issue (#43) 11 days ago. I hope that you haven't put too much time into solving it and that you don't mind that I gave it a go.

This PR + commit is a draft of how to solve this problem, so feel free to give feedback, modify it and so on. The commit also solves two other problems, I can split them into other commits or PRs if you want to. 

**Known bugs**

CircleCI always creates a new release when you push to master, and overwrites the old release with same tag.

**Comment by Rembane** [comment]
# Limitations and future work 

Another limitation is that this CircleCI configuration only tests and builds releases. If it should run after each commit or on each pull request some more work needs to be done.

Every run of CircleCI takes about fifteen minutes. That's a long time and only give 66 free builds a month. We can make this faster by suppling a Docker image with all dependencies installed.

**Comment by diogob** [comment]
@Rembane thanks for PR, much appreciated :D

**Comment by Rembane** [comment]
No worries. It was fun! :D

**Pull request merged**
